spring.application.name=restfulProject

server.servlet.context-path=/spring

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@db:1521:xe}
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:EASYEARTH}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:EASYEARTH}

mybatis.mapper-locations=classpath:/mappers/*.xml
mybatis.type-aliases-package=com.kh.spring
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.configuration.map-underscore-to-camel-case=true

file.upload.path=${user.home}/uploadFiles/

jwt.secret=mysecretkeyTestHOHHOHOHO123qwqwdoiqjd2das0kdasd
jwt.expiration=864000000

springdoc.swagger-ui.path=/swagger-ui
springdoc.packages-to-scan=com.kh.spring

logging.level.root=info
logging.level.com.kh.spring.aop=debug
logging.level.com.kh.spring.board=debug
logging.level.com.kh.spring.member=debug

seoulmap.base-url=https://map.seoul.go.kr
seoulmap.theme-key=KEY301_19ea20abc44b48f5a6ef999b04bb7b31
seoulmap.contents-path=/openapi/v5/{themeKey}/public/themes/contents

ors.base-url=https://api.openrouteservice.org
ors.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjIzNDhlZDgxMzBjOTRjZTdiNWNhMmNjOGRkYmE5MTkwIiwiaCI6Im11cm11cjY0In0=

otp.base-url=http://localhost:8082


# 2. JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
# 실제 실행되는 SQL을 콘솔창에 보여줌
spring.jpa.show-sql=false
# SQL을 보기 좋게 포맷팅
spring.jpa.properties.hibernate.format_sql=false
# 오라클 전용 문법(Dialect) 지정 
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 3. 추가 설정  
# UTF-8 ì¤ì 
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
odsay.api.key=xJSPSRt3edEKrqbmgtpsAgBpOkJEP3cUi8X80mH/p6s

# API ??? ????? ??? (none?? ?? ? ?? ?? ??)
springdoc.swagger-ui.doc-expansion=none
# ?? ??? ?? ???
springdoc.swagger-ui.operations-sorter=alpha

kakao.client-id=061190308402a6afceaaba4ac72b5c83
kakao.client-secret=GuhxDg8x9cbc2DUlMNwytZ7ngp64bhDN
kakao.redirect-uri=http://localhost:5173/kakao/callback

# Naver API
naver.client.id=yOwJ47bc_9ucST4hf_ag
naver.client.secret=2HS1UEr1CU
naver.url.search.news=https://openapi.naver.com/v1/search/news.json

# Gemini API
gemini.api.key=AIzaSyBO7YUZR_Wana-H1Mmj5D6-opXN3YyBwQk